### ISSUE TITLE
Investigate any pricing associated with Map tile providers

### ISSUE THREAD

**Issue by taysea** [grommet/grommet-leaflet#34]
Investigate any pricing associated with Map tile providers. This should include those relied on by leaflet but should also include pricing of competitors like GoogleMaps.

**Providers**
- [Stadia maps](https://stadiamaps.com/pricing/)
- [Maptiler.org ](https://www.maptiler.com/cloud/pricing/)
- [GoogleMaps](https://mapsplatform.google.com/pricing/)
- lots of others, but these two seem like tops

**To do**
- Get a sense of what realistic amount of usage would need to be supported for various service teams
- Come up with an estimate for the above providers of what it would cost each team

Deliverables:
- [x] Discuss with Sriraag and others in GLCP to gain detail on their bandwidth re: budget, planning/timing, etc.: https://github.com/grommet/grommet-leaflet/issues/34#issuecomment-1700066188
- [ ] Summary of pricing, rate limits, etc. to serve as foundation for decisions on which map provider to rely on and why

**Comment by taysea** [comment]
Marking as "blocked" for now until we hear back from Sriraag.

**Comment by SOjaHPE** [comment]
@sriraag provide feedback on usage numbers:

> Hi Scott,
> 
> So, we estimated the number of visits/requests that our device inventory page gets on the platform today. The numbers look like this:
> 
> Average number of requests per day (non-weekend) = 35,508
> Average number of requests per month = 35,508 * 30 = 1,065,240
>  
> I checked with the engineering team and each request here represents an API call made to the backend from the frontend when a user clicks on the “Devices” page on GLP. That gives us a best-case scenario estimate assuming every time a user goes to the device inventory page, they end up opening the map view. Let me know if this information is helpful and if you need any other data.

**Comment by SOjaHPE** [comment]
Usage numbers provided by
- **Amanda V.** 
     - Sustainability Dashboard we are working in a tech preview stage at the moment, not even 5 customers at this point. Our beta goes live in November 15th but that will only be 5 customers as well. I can ask for anticipated projections from the PM if needed.
- **Samantha Jian-Pielak**
     - I have the number of customers we plan to roll out starting in Jan. Other than that, the rest I will have to make assumptions without comparison data. My estimate of the number of page views for the map for the next 4 months (till end of Jan) will be for dev and internal demos: 20 page views / week * 16 weeks = 320 page views total +/- 50%(?). Once we roll it out to customers starting Jan with a couple of months usage data in Adobe Analytics, I should be able to give you a better estimate. 
     - Sustainability Dashboard we are working in a tech preview stage at the moment, not even 5 customers at this point. Our beta goes live in November 15th but that will only be 5 customers as well. I can ask for anticipated projections from the PM if needed.

**Comment by SOjaHPE** [comment]
Posting a link to a spreadsheet to show the hosting provider estimated costs:
[grommet-leaflet map tile provider costs](https://hpe-my.sharepoint.com/:x:/r/personal/scott_oja_hpe_com/Documents/grommet-leaflet%20map%20tile%20provider%20hosting.xlsx?d=wf5679fe367a543d3bc5f9baa4ce8cece&csf=1&web=1&e=P6a17w)

**Comment by sriraag-hpe** [comment]
@SOjaHPE looks like the SharePoint link is broken. I'm unable to access it. 

![image](https://github.com/grommet/grommet-leaflet/assets/143665102/4b09815b-68dd-4ba1-b19f-81f5ba8014de)

**Comment by SOjaHPE** [comment]
@sriraag-hpe thank you for letting me know.. I'll resolve this issue and get back to you asap.

**Comment by SOjaHPE** [comment]
There are three options now being considered:

1. Using a map tile hosting provider, see ticket description for 3 providers
2. Self hosting solution
3. Protomaps.com - CDN approach, storage mechanism / tiles live within a database. It is a single blob file, using HTTP range request to surface the portion of that file, not reading the appropriate tile files.
- this is just an innovation in the storage approach, styling is a json file - need to know what the schema is. This is a very minimal approach, same amount of work as what goes into hosting our own fonts. Might need some sort of permissions, which applications could make the request from the CDN, some restrictions around that. Very minimal overhead.

**Comment by halocline** [comment]
Decision is to move forward with self-hosting the Protomaps tile server - S3 bucket + CDN + Lamda function handling HTTP requests.
